Add assigner for crawl tasks [ZZ-45]
ZaZemiata/ZaZemiata-scraper pull request #14
Opened 2024-11-27 16:36 UTC by batanoffs

Added constant `CRAWL_TASK_STATUS` to store the status for the tasks, please give any suggestions if it should be placed else where . Check line 13 to 20;

2024-11-27 19:34 UTC, DanielDimitrov5 commented on src/assigner.ts
> +};
Import this 'import { CrawlTaskStatus } from "@prisma/client"'
This is the enum type from the schema. From there you can access the statuses directly.
No need for this.

2024-11-27 19:36 UTC, DanielDimitrov5 commented on src/assigner.ts
> +                    source: {
This table is called 'Sources'.
Did you even test it?

2024-11-27 19:36 UTC, DanielDimitrov5 commented on src/assigner.ts
> +                    getTask.status !== CRAWL_TASK_STATUS.IN_PROGRESS
Check this logic once again.

2024-11-27 19:37 UTC, DanielDimitrov5 requested changes
Test the assigner when the issues are fixed.
When you start, it should create just 3 tasks and nothing more.

2024-11-28 17:37 UTC, batanoffs commented
Changes:
- Update logic for assigner as requested. 
- Added try/catch. 
- Updated logger to work with numbers instead of bool

During tests:
- my code didn't generate new warnings
- tested and created 3 tasks, when when status is changed to "COMPLETE", it generated a new one

For review - at line 37:
```js 
const getTask = await prisma.crawlTasks.findFirst({
       where: {
                 status: CrawlTaskStatus.PENDING || CrawlTaskStatus.IN_PROGRESS,
                 source_id: source.id,
               },
       });
```
Should i use findMany instead of findFirst?

2024-11-28 19:15 UTC, DanielDimitrov5 approved these changes
Perfect one!

2024-11-28 19:15 UTC, merged